### ISSUE TITLE
NDK setup link not working

### ISSUE THREAD

**Issue by ugintl** [mail2chromium/Android-Audio-Processing-Using-WebRTC#1]
Link to android webrtc ndk setup not working

**Comment by mail2chromium** [comment]
@ugintl I'm currently working on this repository. Hope It will be ready very soon. 

You can tell me, how may I help you?

**Comment by ugintl** [comment]
I am looking to integrate webrtc into an existing app. It already has chatting.

Something like an sdk. There are few apps like Jami, which allows audio video calls without a server. I would prefer something without a server, but it is ok if I have to use a server.

**Comment by mail2chromium** [comment]
Okay!
WebRTC Native Stack involves a bunch of different domains like
- Audio Processing Module
- Video Processing Module
- Signaling (not recommended), STUN, TURN in the real world.

and many other modules. 

- If you want to make a Peer-to-Peer communication without a centralized server or relay server, You should have knowledge about STUN. 
- Secondly, If you go with a Centralized Server also known as "TURN/ Relay Server". You should have knowledge that how TURN Server works.

I must tell you that STUN and TURN are parallelly working to make communication possible in either of these scenarios between Android/iOS Peers.

Which one of these modules of WebRTC, do you want to integrate into your application?

**Comment by mail2chromium** [comment]
@ugintl 
Link is now public, you can revisit:
[Android-Native-Development-For-WebRTC](https://github.com/mail2chromium/Android-Native-Development-For-WebRTC )
