### ISSUE TITLE
System.loadLibrary("soundtouch") cause fatal crash

### ISSUE THREAD

**Issue by ipdental** [mail2chromium/Android-Audio-Processing-Using-WebRTC#2]
System Information:
OS: Windows 10 64bit
IDE: Android Studio 3.6.2
JDK 1.8
NDK r21

Steps to Repro:
Downloaded git
On Sync Build I get following message in red color
17:00	Unsupported Modules Detected: Compilation is not supported for following modules: Android-Audio-Processing-Using-WebRTC. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
On running the code, system crashes at runtime on calling System.loadLibrary("soundtouch") in JNISoundTouch class

Question - What am I doing something wrong here? Since I am a newbie to Android. How can I correct it.

**Comment by mail2chromium** [comment]
Sorry for being late. I have compiled the Library using `NDK-r13`, also by using `NDK-r20`. I will update you after checking it with `NDK-r21`. 
For now, try these following steps:

0- Go to File -> Invalidate Caches/Restart

1- Close the project

2- Close Android Studio IDE

3- Delete the `.idea` directory

4- Delete all `.iml` files

5- Open Android Studio IDE and import the project

I hope, it will work.

**Comment by ipdental** [comment]
It is not about NDK version. 

The error is that JNI files for "soundtouch" are missing.

**Comment by mail2chromium** [comment]
Oh, my mistake!
I just forgot to compile the library for both architectures [libsoundtouch.so](https://github.com/mail2chromium/Android-Audio-Processing-Using-WebRTC/tree/master/app/src/main/libs/arm64-v8a), [libsoundtouch.so](https://github.com/mail2chromium/Android-Audio-Processing-Using-WebRTC/tree/master/app/src/main/libs/armeabi-v7a). You can check this library and again use it. Hopefully, it will work.

**Comment by ipdental** [comment]
No Android Studio will require everything. Source, wrapper cpp, .mk files everything.

**Comment by mail2chromium** [comment]
@ipdental, When you have just a compiled file which is either of static (`*.a`) or a shared library(`*.so`), then you can use them in your project. There is no need for any kind of 
- Native Source Code
- Android/Application make files

until and unless you want them to recompile and rebuild by yourself or want changes in your native stack. 
So, for this project, I have already compiled these files and there are present in **libs** directory.
If you want to build your own library, then have a look at this [Android-Native-Development-For-WebRTC](https://github.com/mail2chromium/Android-Native-Development-For-WebRTC).
Good luck!
