### ISSUE TITLE
Any noise gate implementation on webrtc?

### ISSUE THREAD

**Issue by aviadavi** [mail2chromium/Android-Audio-Processing-Using-WebRTC#3]

**Comment by mail2chromium** [comment]
@aviadavi Thanks for reaching me out. I am working on Standalone WebRtc Noise Suppress and RNNoise, I hopefully this would be done really soon. 

Please let me know, If I can assist you.

**Comment by aviadavi** [comment]
Basically I'm using M84. RNNoise is not part of it right?
I'm looking for a very basic noise gate..

**Comment by mail2chromium** [comment]
I am not working on any branch like M84. I am working on the master branch. There is a possibility that WebRtc may include RNNoise in there future checkouts. Secondly, I am working on a standalone AEC, AGC, NS and VAD module. 

What I can help you to direct towards possible solutions, Please Visit.
- https://github.com/jagger2048/WebRtc_noise_suppression
- https://programmersought.com/article/35662571232/
