### ISSUE TITLE
Ability to compile x86_64 and x86 architecture？

### ISSUE THREAD

**Issue by lujiasheng** [mail2chromium/Android-Audio-Processing-Using-WebRTC#7]

**Comment by mail2chromium** [comment]
Thanks for your concerns. I will update the repository with the required changes.

**Comment by mail2chromium** [comment]
The Initial Purpose of using this Audio Processing Module was to provide Android Level Debugging of the WebRTC Native Stack. In this year, I am going to improve this Audio Processing Algorithm based on WebRTC's Latest `m110` branch.
